parameters:
    gatekeeper.class: GateKeeper\GateKeeper
    gatekeeper.access.allow.class: GateKeeperBundle\Access\Allow
    gatekeeper.access.deny.class: GateKeeperBundle\Access\Deny

services:
    gatekeeper:
        class: %gatekeeper.class%

    gatekeeper.repository.dummy:
        class: GateKeeper\Repository\DummyRepository

    gatekeeper.gates_provider.dummy:
        class: GateKeeper\Provider\DummyGatesProvider

    gatekeeper.voter:
        class: GateKeeperBundle\Voter\GateKeeper
        arguments: ["@gatekeeper"]
        tags:
          - { name: security.voter }

    gatekeeper.access.allow:
        public: false
        class: %gatekeeper.access.allow.class%
        tags:
          - { name: gatekeeper.access }

    gatekeeper.access.deny:
        public: false
        class: %gatekeeper.access.deny.class%
        tags:
          - { name: gatekeeper.access }