services:
    GateKeeper\GateKeeper:
        class: GateKeeper\GateKeeper
        public: true

    gatekeeper:
        alias: GateKeeper\GateKeeper
        deprecated: true
        public: true

    gatekeeper.repository.dummy:
        class: GateKeeper\Repository\DummyRepository

    gatekeeper.gates_provider.dummy:
        class: GateKeeper\Provider\DummyGatesProvider

    gatekeeper.voter:
        class: GateKeeperBundle\Voter\GateKeeper
        arguments: ['@GateKeeper\GateKeeper']
        tags:
          - { name: security.voter }

    gatekeeper.access.allow:
        public: false
        class: GateKeeperBundle\Access\Allow
        tags:
          - { name: gatekeeper.access }

    gatekeeper.access.deny:
        public: false
        class: GateKeeperBundle\Access\Deny
        tags:
          - { name: gatekeeper.access }
